//
// Created by mrbueno on 19/4/20.
//

#ifndef FROMIDE_PIN_H
#define FROMIDE_PIN_H

#define PIN_LEFT_GEARMOTOR_PWD 5
#define PIN_LEFT_GEARMOTOR_AHEAD 6
#define PIN_LEFT_GEARMOTOR_REVERSE 7

#define PIN_RIGHT_GEARMOTOR_PWD 10
#define PIN_RIGHT_GEARMOTOR_AHEAD 8
#define PIN_RIGHT_GEARMOTOR_REVERSE 9

#define PIN_ULTRASONIC_TRIGGER 3
#define PIN_ULTRASONIC_ECHO 11

#endif //FROMIDE_PIN_H
